# -*- coding: utf-8 -*-
# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www.gnu.org/licenses/>.

# frameworks/base/core/res/AndroidManifest.xml
# ####################### PERMISSIONS ################################


DVM_PERMISSIONS = {
    "MANIFEST_PERMISSION": {
        "SEND_SMS": ["dangerous", "发送短信", "允许应用程序发送短信. 恶意应用程序可能会不通过用户的确认就发送收费信息."],
        "SEND_SMS_NO_CONFIRMATION": ["dangerous", "发送短信", "没有用户输入或确认就通过消息传递应用发送sms消息"],
        "CALL_PHONE": ["dangerous", "直接拨打电话号码", "应用程序可以略过用户的允许，调用电话号码. 恶意应用程序可能会导致用户的话费异常. 请注意,这并不允许应用程序拨打紧急号码."],
        "RECEIVE_SMS": ["dangerous", "接收短信", "允许应用程序接收和处理短信. 恶意应用程序可能没有通知用户，就进行监控或者删除用户的消息."],
        "RECEIVE_MMS": ["dangerous", "接收彩信", "允许应用程序接收和处理彩信.恶意应用程序可能没有通知用户就进行监控或者删除用户的消息."],
        "READ_SMS": ["dangerous", "读取短信或彩信", "允许应用程序读取存储在用户手机或者sim卡上的短信. 恶意应用可能会读取用户的机密信息."],
        "WRITE_SMS": ["dangerous", "修改短信或者彩信", "允许应用程序编辑存储在用户的手机或SIM卡的短信. 恶意应用程序可能会删除用户的信息."],
        "RECEIVE_WAP_PUSH": ["dangerous", "接收无线应用协议", "允许应用程序来接收和处理WAP消息。恶意应用可能会监视用户的短信或删除短信而不向用户显示."],
        "READ_CONTACTS": ["dangerous", "读取联系人数据", "允许应用程序读取储存在用户的手机上的所有联系人(地址)数据. 恶意应用程序可以使用这个数据发送给其他人."],
        "WRITE_CONTACTS": ["dangerous", "写联系人数据", "允许应用程序修改存储在用户手机上的联系人（地址）数据. 恶意应用程序可以使用这个来删除或修改用户的联系资料."],
        "READ_PROFILE": ["dangerous", "读取用户的个人资料数据", "允许应用程序读取用户的个人资料数据."],
        "WRITE_PROFILE": ["dangerous", "写用户的个人配置文件数据", "允许一个应用程序编写(但不是读)用户的个人配置文件数据."],
        "READ_SOCIAL_STREAM": ["dangerous", "读取用户的社会流", "允许应用程序读取用户的社会流."],
        "WRITE_SOCIAL_STREAM": ["dangerous", "写用户的社会流", "允许应用程序写（但不是读）用户的社会流数据."],
        "READ_CALENDAR": ["dangerous", "读日历事件", "允许应用程序读取所有存储在用户手机上的日历事件. 恶意应用程序可以使用这个日历事件发送给其他人."],
        "WRITE_CALENDAR": ["dangerous", "添加或修改日历事件、给客人发送电子邮件",
                           "允许应用程序添加或更改日历事件,这可能会给客人发电子邮件。恶意应用程序可以使用这个来删除或修改用户的日历事件或寄电子邮件给客人."],
        "READ_USER_DICTIONARY": ["dangerous", "读用户定义的词典", "允许应用程序读取用户可能已经存储在用户词典中的私有字词，名称和短语。"],
        "WRITE_USER_DICTIONARY": ["normal", "写用户定义的词典", "允许一个应用程序编写新单词到用户字典。"],
        "READ_HISTORY_BOOKMARKS": ["dangerous", "阅读浏览器的历史和书签", "允许应用程序读取所有浏览器的url访问和所有的浏览器的书签."],
        "WRITE_HISTORY_BOOKMARKS": ["dangerous", "写浏览器的历史和书签", "允许应用程序修改存储在手机上的浏览器的历史或书签。恶意应用程序可借此清除或修改浏览器的数据."],
        "SET_ALARM": ["normal", "设置报警闹钟", "允许应用程序在设置中安装报警的闹钟应用程序，一些闹钟应用程序可能不会实现这个特性."],
        "ACCESS_FINE_LOCATION": ["dangerous", "准确的（GPS）位置", "获得精确的位置来源,如手机上可用的全球定位系统, 恶意应用程序可借此确定用户身在何处，并可能消耗额外的电池电量."],
        "ACCESS_COARSE_LOCATION": ["dangerous", "粗略(基于网络的)位置", "访问粗略的位置来源,如移动网络数据库,确定一个近似的手机位置. 恶意应用程序可以使用这个来确定用户在哪里."],
        "ACCESS_MOCK_LOCATION": ["dangerous", "模拟源位置进行测试", "恶意应用程序可以使用这个覆盖返回的位置，或真实地点来源，如GPS或网络提供者."],
        "ACCESS_LOCATION_EXTRA_COMMANDS": ["normal", "访问额外的位置提供者命令", "访问额外的位置提供者命令。恶意应用程序可以使用这个干扰GPS或其他位置的操作."],
        "INSTALL_LOCATION_PROVIDER": ["signatureOrSystem", "允许安装位置提供",
                                      "创建模拟源位置进行测试。恶意应用程序可以使用这个覆盖返回的位置或状态的真实地点来源，如GPS或网络提供商,或外部源监测、报告用户的位置."],
        "INTERNET": ["dangerous", "完整的互联网接入", "允许应用程序创建网络套接"],
        "ACCESS_NETWORK_STATE": ["normal", "查看网络状态", "允许一个应用程序查看所有网络的状态."],
        "ACCESS_WIFI_STATE": ["normal", "查看无线状态", "允许一个应用程序来查看wi-fi信息的状态."],
        "BLUETOOTH": ["dangerous", "创建蓝牙连接", "允许应用程序配置本地视图蓝牙电话,并接受与配对设备连接。."],
        "NFC": ["dangerous", "控制近场通信", "允许应用程序与近距离无线通信(NFC)标签、卡片和读卡器."],
        "USE_SIP": ["dangerous", "打/接收互联网电话", "允许一个应用程序使用SIP服务/接收互联网电话."],
        "ACCOUNT_MANAGER": ["signature", "作为客户经理服务", "允许应用程序验证打电话账户的身份"],
        "GET_ACCOUNTS": ["normal", "发现已知的账户", "允许应用程序访问帐户的电话列表."],
        "AUTHENTICATE_ACCOUNTS": ["dangerous", "作为一个帐户身份", "允许使用客户经理的帐户身份验证功能，包括创建帐户以及获取和设置其密码的应用程序."],
        "USE_CREDENTIALS": ["dangerous", "使用帐户的身份验证凭证", "允许应用程序请求身份验证令牌."],
        "MANAGE_ACCOUNTS": ["dangerous", "管理账户列表", "允许应用程序执行操作,比如添加、删除账户和删除密码."],
        "MODIFY_AUDIO_SETTINGS": ["dangerous", "改变用户的音频设置", "允许应用程序修改全局音频设置,如音量和路由."],
        "RECORD_AUDIO": ["dangerous", "记录音频", "允许应用程序访问路径的音频记录."],
        "CAMERA": ["dangerous", "拍照和视频", "允许应用程序使用摄像头拍照和视频。这允许应用程序来收集相机在任何时候看到的图像."],
        "VIBRATE": ["normal", "控制振动器", "允许应用程序控制振动器."],
        "FLASHLIGHT": ["normal", "控制手电筒", "允许应用程序控制手电筒."],
        "ACCESS_USB": ["signatureOrSystem", "访问USB设备", "允许应用程序访问USB设备."],
        "HARDWARE_TEST": ["signature", "测试硬件", "允许应用程序来控制各种外接硬件测试的目的."],
        "PROCESS_OUTGOING_CALLS": ["dangerous", "拦截即将拨出的电话", "允许应用程序处理外拨电话或更改要拨打的号码。恶意应用可能会监视，重定向或阻止外拨电话."],
        "MODIFY_PHONE_STATE": ["signatureOrSystem", "修改电话状态", "允许应用控制设备的电话功能。应用程序拥有此权限可自行切换网络，打开手机和关闭无线电之类的，而不会通知用户."],
        "READ_PHONE_STATE": ["dangerous", "读手机状态和身份", "允许应用程序访问手机的功能设备。应用程序使用这个许可可以确定这款手机的号码和序列号,是否主动打电话,电话被连接到等等."],
        "WRITE_EXTERNAL_STORAGE": ["dangerous", "读取/修改/删除SD卡的内容", "允许应用程序写入SD卡，可能会造成重要数据被覆盖。"],
        "READ_EXTERNAL_STORAGE": ["dangerous", "读取SD卡内容", "允许应用程序读取SD卡."],
        "WRITE_SETTINGS": ["dangerous", "修改全局系统设置", "允许应用程序修改系统的设置数据。恶意应用程序可以恶化系统配置."],
        "WRITE_SECURE_SETTINGS": ["signatureOrSystem", "修改安全系统设置", "允许应用程序修改系统的安全设置数据。普通应用程序不常用."],
        "WRITE_GSERVICES": ["signatureOrSystem", "修改谷歌地图服务", "允许应用程序修改地图的谷歌服务。普通应用程序不常用."],
        "EXPAND_STATUS_BAR": ["normal", "展开/折叠状态栏", "允许应用程序展开或折叠状态栏."],
        "GET_TASKS": ["dangerous", "获取正在运行的应用程序", "允许应用程序检索有关当前和最近运行的任务信息。恶意应用程序可借此发现有关其他应用的私密信息."],
        "REORDER_TASKS": ["dangerous", "重新排序运行的应用程序", "允许移动任务，前台和后台的应用程序。恶意应用程序可借此强行进入前端，而不受用户的控制."],
        "CHANGE_CONFIGURATION": ["dangerous", "修改用户的UI设置", "允许应用程序来改变当前的配置,如区域或整体的字体大小."],
        "RESTART_PACKAGES": ["normal", "结束后台进程", "允许应用程序结束后台运行的其他应用程序,即使存储空间并不低."],
        "KILL_BACKGROUND_PROCESSES": ["normal", "结束后台进程", "允许应用程序结束后台运行的其他应用程序,即使存储空间并不低."],
        "FORCE_STOP_PACKAGES": ["signature", "强制停止其他应用程序", "允许应用程序停止强行的其他应用程序."],
        "DUMP": ["signatureOrSystem", "检索系统内部状态", "允许应用程序检索系统的内部状态。恶意应用程序可能会获取他们一般不需要的各种各样的私人和安全信息,."],
        "SYSTEM_ALERT_WINDOW": ["dangerous", "显示系统级警报", "允许应用程序来显示系统级窗口。恶意应用程序可以接管手机的整个屏幕."],
        "SET_ANIMATION_SCALE": ["dangerous", "修改全局的动画速度", "允许应用程序改变全局动画速度(快或慢的动画)."],
        "PERSISTENT_ACTIVITY": ["dangerous", "使应用程序一直运行", "允许应用程序持续运行他自己，以至于不能使用其他应用程序."],
        "GET_PACKAGE_SIZE": ["normal", "测量应用程序存储空间", "允许应用程序检索它的代码、数据和缓存大小."],
        "SET_PREFERRED_APPLICATIONS": ["signature", "设置首选应用程序",
                                       "允许应用程序首选应用程序修改。这可以允许恶意应用程序默默地改变运行的应用程序,欺骗用户的现有应用程序收集从用户的私人数据."],
        "RECEIVE_BOOT_COMPLETED": ["normal", "开机自启动", "允许应用程序开机自启动，这会延长开机时间，应用程序持续运行进而使手机变慢."],
        "BROADCAST_STICKY": ["normal", "发送粘连广播", "允许一个应用程序发送粘连广播,广播结束后，恶意应用程序可以使用过多的内存导致手机变慢或不稳定."],
        "WAKE_LOCK": ["dangerous", "防止手机休眠", "允许应用程序阻止手机休眠."],
        "SET_WALLPAPER": ["normal", "设置壁纸", "允许应用程序设置系统壁纸."],
        "SET_WALLPAPER_HINTS": ["normal", "设置壁纸大小提示", "允许应用程序设置系统壁纸大小时提示."],
        "SET_TIME": ["signatureOrSystem", "设置时间", "允许应用程序修改手机的时钟时间."],
        "SET_TIME_ZONE": ["dangerous", "设置时区", "允许应用程序修改手机的时区."],
        "MOUNT_UNMOUNT_FILESYSTEMS": ["dangerous", "挂载和卸载文件系统", "允许应用程序为移动存储挂载和卸载文件系统."],
        "MOUNT_FORMAT_FILESYSTEMS": ["dangerous", "外部存储格式", "允许应用程序格式化存储空间."],
        "ASEC_ACCESS": ["signature", "读取内存信息 ", "允许应用程序获取内存信息."],
        "ASEC_CREATE": ["signature", "创建内存信息", "允许应用程序创建内存信息."],
        "ASEC_DESTROY": ["signature", "销毁内存信息", "允许应用程序销毁内存信息."],
        "ASEC_MOUNT_UNMOUNT": ["signature", "内部存储挂载/卸载", "允许应用程序内部存储挂载/卸载."],
        "ASEC_RENAME": ["signature", "重命名内部存储", "允许应用程序重命名内部存储."],
        "DISABLE_KEYGUARD": ["dangerous", "禁用按键锁定", "允许应用程序禁用一切相关的密码安全的关键锁。一个合法的例子就是让手机上接听电话时停用键锁，然后在通话结束后重新启用键锁."],
        "READ_SYNC_SETTINGS": ["normal", "读同步设置", "允许应用程序读取同步设置,如是否启用同步联系人."],
        "WRITE_SYNC_SETTINGS": ["dangerous", "写同步设置", "允许一个应用程序修改同步设置,比如是否启用同步联系人."],
        "READ_SYNC_STATS": ["normal", "读同步数据", "允许应用程序读取同步数据;例如同步发生的历史."],
        "WRITE_APN_SETTINGS": ["dangerous", "设置访问点名称", "允许应用程序修改APN设置,如APN的代理和端口."],
        "SUBSCRIBED_FEEDS_READ": ["normal", "阅读订阅的提要", "允许应用程序来接收当前同步源的详细信息."],
        "SUBSCRIBED_FEEDS_WRITE": ["dangerous", "写订阅的提要", "允许应用程序修改用户当前同步提要。这可能允许恶意应用程序来改变用户的同步源."],
        "CHANGE_NETWORK_STATE": ["dangerous", "改变网络连接", "允许应用程序改变网络连接的状态."],
        "CHANGE_WIFI_STATE": ["dangerous", "改变WiFi的状态", "允许应用程序连接和断开无线接入点和修改无线网络配置."],
        "CHANGE_WIFI_MULTICAST_STATE": ["dangerous", "允许无线多播接待",
                                        "允许应用程序接收没有直接发给用户设备的数据包。当附近发现服务提供时，这可能是有用的。它将比non-multicast模式使用更多的权力."],
        "BLUETOOTH_ADMIN": ["dangerous", "蓝牙管理", "允许应用程序配置本地蓝牙电话,发现和远程设备配对."],
        "CLEAR_APP_CACHE": ["dangerous", "删除所有应用程序缓存数据", "允许应用程序删除存储在应用程序缓存目录中的免费电话。访问通常是受限于系统的进程."],
        "READ_LOGS": ["dangerous", "阅读敏感的日志数据", " 允许应用程序读取系统的各种日志文件。这使得它可以发现用户用手机做什么,可能包括个人或私人信息."],
        "SET_DEBUG_APP": ["dangerous", "启用应用程序调试", "允许应用程序打开调试其他应用程序。恶意应用程序可借此终止其他应用程序."],
        "SET_PROCESS_LIMIT": ["dangerous", "限制进程的运行数量", "允许应用程序控制运行的最大进程数量。从不需要使用常见的应用."],
        "SET_ALWAYS_FINISH": ["dangerous", "关闭所有的后台应用程序", "允许应用程序控制activities是否总是一后台运行就结束。不需要共同的应用程序."],
        "SIGNAL_PERSISTENT_PROCESSES": ["dangerous", "给应用程序发送Linux信号", "允许应用程序请求将提供的信号发送给所有持续进行的进程."],
        "DIAGNOSTIC": ["signature", "读/写资源属于自己的特征",
                       "允许应用程序读取和写入诊断组所拥有的任何资源;例如，文件在/ dev目录。这可能会影响系统的稳定性和安全性.这应该只被用于制造商或运营商的硬件诊断."],
        "STATUS_BAR": ["signatureOrSystem", "停用或修改状态栏", "允许应用程序停用状态栏或者增删系统图标."],
        "STATUS_BAR_SERVICE": ["signature", "状态栏", "允许应用程序可以在状态栏显示."],
        "FORCE_BACK": ["signature", "强制关闭应用程序", "允许程序的任何活动强行在前台关闭并返回。不需要普通应用."],
        "UPDATE_DEVICE_STATS": ["signatureOrSystem", "修改电池的统计数据", "允许电池统计信息的修改。不建议普遍应用."],
        "INTERNAL_SYSTEM_WINDOW": ["signature", "显示未授权的窗口", "允许创建 windows旨在内部系统使用的用户界面。不建议普遍应用."],
        "MANAGE_APP_TOKENS": ["signature", "管理应用程序令牌", "允许应用程序创建和管理自己的令牌，从而绕开他们共同的排序。不需要普遍应用."],
        "INJECT_EVENTS": ["signature", "按键和控制按钮", "允许应用程序将自身的输入活动（例如按键操作等）提供给其他应用程序。恶意应用程序可借此操控手机."],
        "SET_ACTIVITY_WATCHER": ["signature", "监视和控制所有应用程序启动",
                                 "允许应用程序监视和控制系统是如何启动活动的。恶意应用可能会完全破坏系统。此权限只需要开发，从来不为普通电话使用."],
        "SHUTDOWN": ["signature", "部分关闭", "使活动管理器进入关机状态。不执行完全关机."],
        "STOP_APP_SWITCHES": ["signature", "阻止app交换", "防止用户切换到另一个应用程序."],
        "READ_INPUT_STATE": ["signature", "记录键入和动作", "允许应用程序观察用户与其他应用程序交互时按下的按键即使是输入密码。不需要普遍应用."],
        "BIND_INPUT_METHOD": ["signature", "绑定到输入方法", "允许应用绑定到输入法的顶级接口。不需要普遍应用."],
        "BIND_WALLPAPER": ["signatureOrSystem", "绑定到壁纸", "允许夹持器绑定到壁纸的顶级接口。不需要普遍应用."],
        "BIND_DEVICE_ADMIN": ["signature", "与设备管理互动", "允许手机用户发送intent给设备管理员。不需要普遍应用."],
        "SET_ORIENTATION": ["signature", "更改屏幕显示方向", "允许应用程序随时更改屏幕的旋转。不需要普遍应用."],
        "INSTALL_PACKAGES": ["signatureOrSystem", "直接安装应用程序", "允许安装新的或更新的Android包的应用程序。恶意应用程序可借此添加具有任意权限的新应用."],
        "CLEAR_APP_USER_DATA": ["signature", "删除其他应用程序的数据", "允许应用程序清除用户数据."],
        "DELETE_CACHE_FILES": ["signatureOrSystem", "删除其他应用程序的缓存", "允许应用程序删除缓存文件."],
        "DELETE_PACKAGES": ["signatureOrSystem", "删除应用程序", "允许应用程序删除Android包。恶意应用程序可借此删除重要的应用."],
        "MOVE_PACKAGE": ["signatureOrSystem", "移动应用资源", "允许应用程序从内部移动应用程序资源，外部媒体，反之亦然."],
        "CHANGE_COMPONENT_ENABLED_STATE": ["signatureOrSystem", "启用或禁用应用程序组件",
                                           "允许应用程序更改另一应用程序的组件是否启用。恶意应用程序可借此停用重要的手机功能。要小心权限是很重要的，因为它可以使应用程序组件陷入不可用，不一致或不稳定的状态."],
        "ACCESS_SURFACE_FLINGER": ["signature", "访问服务端", "允许应用程序使用服务端的低级功能."],
        "READ_FRAME_BUFFER": ["signature", "读取帧缓冲区", "允许应用程序读取帧缓冲区的内容."],
        "BRICK": ["signature", "永久停用手机", "允许应用程序永久停用整个手机。这很危险."],
        "REBOOT": ["signatureOrSystem", "强制手机重启", "允许应用程序强制重启手机."],
        "DEVICE_POWER": ["signature", "开启或关闭手机", "允许应用程序打开或关闭手机."],
        "FACTORY_TEST": ["signature", "在出厂测试模式下运行", "作为低级别制造商测试运行，允许完全访问手机硬件。仅当手机在制造商测试模式下运行提供."],
        "BROADCAST_PACKAGE_REMOVED": ["signature", "发送包已删除的广播", "允许应用程序播放应用程序包已经移除的通知。恶意应用程序可借此终止正在运行的其他应用程序."],
        "BROADCAST_SMS": ["signature", "发送短信接收的广播", "允许应用程序广播已收到短信的通知。恶意应用程序可能会借此伪造收到的短信."],
        "BROADCAST_WAP_PUSH": ["signature", "发送WAP-PUSH收到的广播",
                               "允许应用程序广播已收到WAP-PUSH消息的通知。恶意应用程序可能会借此乱发彩信或恶意变种悄悄替换网页的内容."],
        "MASTER_CLEAR": ["signatureOrSystem", "系统复位到出厂默认设置", "允许应用程序将系统完全重置为出厂设置，即清除所有数据，配置和安装的应用程序."],
        "CALL_PRIVILEGED": ["signatureOrSystem", "直接拨打任何电话号码", "允许应用程序拨打任何号码，包括紧急电话号码，无需用户干预。恶意应用程序可能会骚扰和非法呼叫紧急服务."],
        "PERFORM_CDMA_PROVISIONING": ["signatureOrSystem", "直接启动CDMA电话设置", "允许应用程序启动CDMA服务。恶意应用程序可能会启动不必要的CDMA配置"],
        "CONTROL_LOCATION_UPDATES": ["signatureOrSystem", "控制位置更新通知", "允许从无线模块启用/禁用位置更新提示。不建议普遍应用."],
        "ACCESS_CHECKIN_PROPERTIES": ["signatureOrSystem", "访问签到属性", "允许读/写访问由登记服务上传的属性。不建议普遍应用."],
        "PACKAGE_USAGE_STATS": ["signature", "更新组件使用情况统计", "允许收集组件使用情况统计的修改。不建议普遍应用."],
        "BATTERY_STATS": ["normal", "修改电池统计信息", "允许电池统计信息的修改。不建议普遍应用."],
        "BACKUP": ["signatureOrSystem", "控制系统备份和恢复", "  允许应用程序来控制系统\的备份和恢复机制。不建议普遍应用."],
        "BIND_APPWIDGET": ["signatureOrSystem", "选择窗口小部件",
                           "允许应用程序知道哪些部件可以使用该应用程序的系统。这个许可,应用程序可以给其他应用程序访问个人数据的通道。不建议普遍应用."],
        "GLOBAL_SEARCH": ["signatureOrSystem", "", ""],
        "GLOBAL_SEARCH_CONTROL": ["signature", "", ""],
        "SET_WALLPAPER_COMPONENT": ["signatureOrSystem", "", ""],
        "ACCESS_CACHE_FILESYSTEM": ["signatureOrSystem", "访问缓存文件系统", "允许应用程序读取和写入缓存文件系统."],
        "COPY_PROTECTED_DATA": ["signature", "允许调用默认容器服务复制内容. 不建议普遍应用.", "允许调用默认容器服务复制内容。不建议普遍应用."],
        "C2D_MESSAGE": ["signature", "允许云到设备的消息传递", "允许应用程序接收推送通知."],

        "ADD_VOICEMAIL": ["dangerous", "添加语音邮件插入系统", "允许应用程序添加语音邮件进入系统."],
    },

    "MANIFEST_PERMISSION_GROUP":
        {

            "ACCOUNTS": "权限直接访问账户管理通过账户管理员.",
            "COST_MONEY": "用于可使用户未经其直接参与就花钱的权限.",
            "DEVELOPMENT_TOOLS": "权限组与开发有关的特征.",
            "HARDWARE_CONTROLS": "用于提供直接访问硬件设备上的权限.",
            "LOCATION": "用于权限允许访问用户的当前位置.",
            "MESSAGES": "用于权限,允许应用程序代表用户发送消息或拦截消息，这被用户接受.",
            "NETWORK": "用于提供访问网络服务的权限.",
            "PERSONAL_INFO": "用于提供访问用户的隐私数据的权限，如联系人，日历事件，电子邮件等.",
            "PHONE_CALLS": "用于那些与访问和修改电话状态相关联的权限：拦截拨出电话，阅读和修改手机状态.",
            "STORAGE": "权限组与相关的SD卡访问.",
            "SYSTEM_TOOLS": "权限组与相关的系统API.",
        },
}
